### ISSUE TITLE
Crash 1.20.1 fabric

### ISSUE THREAD

**Issue by XeweIs** [InLieuOfLuna/find#10]
When installing a mod into a build I get this error
> [19:25:23] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/SystemX/AppData/Roaming/.tlauncher/legacy/Minecraft/game/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
> [19:25:23] [main/INFO]: Compatibility level set to JAVA_17
> [19:25:24] [main/WARN]: Reference map 'letsdo-beachparty-fabric-fabric-refmap.json' for beachparty.mixins.json could not be read. If this is a development environment you can ignore this message
> [19:25:24] [main/WARN]: Reference map 'cinderscapes-worldgen-refmap.json' for mixins.cinderscapes-worldgen.json could not be read. If this is a development environment you can ignore this message
> [19:25:24] [main/INFO]: Preloading Debugify
> [19:25:24] [main/WARN]: Reference map 'dynmus-fabric-refmap.json' for dynmus.mixins.json could not be read. If this is a development environment you can ignore this message
> [19:25:24] [main/WARN]: Reference map 'fennecfox-fabric-1.20.1-refmap.json' for fennecfox.mixins.json could not be read. If this is a development environment you can ignore this message
> [19:25:24] [main/WARN]: Reference map 'client-fennecfox-fabric-1.20.1-refmap.json' for fennecfox.client.mixins.json could not be read. If this is a development environment you can ignore this message
> [19:25:24] [main/WARN]: Reference map 'de-guntram-mcmod-fabrictools-refmap.json' for mixins.de-guntram-mcmod-fabrictools.json could not be read. If this is a development environment you can ignore this message
> [19:25:24] [main/WARN]: Reference map 'graveyard-FABRIC-fabric-refmap.json' for graveyard-fabric.mixins.json could not be read. If this is a development environment you can ignore this message
> [19:25:24] [main/WARN]: Reference map 'InvMove-mc1.20_fabric-refmap.json' for invmove-fabric.mixins.json could not be read. If this is a development environment you can ignore this message
> [19:25:24] [main/INFO]: Loaded configuration file for Lithium: 115 options available, 4 override(s) found
> [19:25:24] [main/WARN]: Reference map 'mythic-mounts-refmap.json' for mythic-mounts.mixins.json could not be read. If this is a development environment you can ignore this message
> [19:25:24] [main/WARN]: [Satin] Iris is present, custom block renders will not work
> [19:25:24] [main/WARN]: Reference map 'seamless-loading-screen-fabric-refmap.json' for seamless_loading_screen-fabric.mixins.json could not be read. If this is a development environment you can ignore this message
> [19:25:24] [main/WARN]: Reference map 'simplyswords-fabric-refmap.json' for simplyswords.mixins.json could not be read. If this is a development environment you can ignore this message
> [19:25:24] [main/INFO]: Loaded configuration file for Sodium: 41 options available, 5 override(s) found
> [19:25:24] [main/INFO]: Loaded configuration file for Sodium Extra: 32 options available, 0 override(s) found
> [19:25:24] [main/WARN]: Reference map 'static-content-refmap.json' for static-content.mixins.json could not be read. If this is a development environment you can ignore this message
> [19:25:24] [main/WARN]: Reference map 'wakes-refmap.json' for wakes.mixins.json could not be read. If this is a development environment you can ignore this message
> [19:25:25] [main/WARN]: Error loading class: io/github/apace100/apoli/power/factory/condition/ConditionFactory (java.lang.ClassNotFoundException: io/github/apace100/apoli/power/factory/condition/ConditionFactory)
> [19:25:25] [main/WARN]: @Mixin target io.github.apace100.apoli.power.factory.condition.ConditionFactory was not found mixins.artifacts.fabric.json:compat.origins.ConditionFactoryAccessor from mod artifacts
> [19:25:25] [main/INFO]: CameraOverhaul: Using modern mixin 'mirsario.cameraoverhaul.fabric.mixins.modern.CameraMixin'.
> [19:25:25] [main/INFO]: CameraOverhaul: Using modern mixin 'mirsario.cameraoverhaul.fabric.mixins.modern.GameRendererMixin'.
> [19:25:25] [main/INFO]: CameraOverhaul: Skipping legacy mixin 'mirsario.cameraoverhaul.fabric.mixins.legacy.LegacyCameraMixin'.
> [19:25:25] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/model/quad/blender/LinearColorBlender (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/model/quad/blender/LinearColorBlender)
> [19:25:25] [main/WARN]: Error loading class: net/minecraft/client/font/FontManager$1 (java.lang.ClassNotFoundException: net/minecraft/client/font/FontManager$1)
> [19:25:25] [main/WARN]: @Mixin target net/minecraft/client/font/FontManager$1 was not found dashloader.mixins.json:option.cache.font.FontManagerOverride from mod dashloader
> [19:25:25] [main/WARN]: Force disabled MC-121772 because it only applies to OS: MAC
> [19:25:25] [main/WARN]: Force disabled MC-122477 because it only applies to OS: LINUX
> [19:25:25] [main/WARN]: Force disabled MC-176559 because it's conflicting with: fabric-api
> [19:25:25] [main/WARN]: Force disabled MC-22882 because it only applies to OS: MAC
> [19:25:25] [main/WARN]: Force-disabling mixin 'ai.task.memory_change_counting.BrainMixin' as rule 'mixin.ai.task.memory_change_counting' (added by mods [smartbrainlib]) disables it and children
> [19:25:25] [main/WARN]: Force-disabling mixin 'ai.task.memory_change_counting.MultiTickTaskMixin' as rule 'mixin.ai.task.memory_change_counting' (added by mods [smartbrainlib]) disables it and children
> [19:25:25] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
> [19:25:25] [main/WARN]: Force-disabling mixin 'alloc.chunk_ticking.ServerChunkManagerMixin' as rule 'mixin.alloc.chunk_ticking' (added by mods [servercore]) disables it and children
> [19:25:25] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
> [19:25:25] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/occlusion/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/occlusion/BlockOcclusionCache)
> [19:25:25] [main/WARN]: Error loading class: fr/catcore/server/translations/api/resource/language/SystemDelegatedLanguage (java.lang.ClassNotFoundException: fr/catcore/server/translations/api/resource/language/SystemDelegatedLanguage)
> [19:25:26] [main/WARN]: Force-disabling mixin 'features.gui.screen.LevelLoadingScreenMixin' as rule 'mixin.features.gui.screen' (added by mods [seamless_loading_screen]) disables it and children
> [19:25:26] [main/WARN]: Force-disabling mixin 'features.render.entity.CuboidMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
> [19:25:26] [main/WARN]: Force-disabling mixin 'features.render.entity.ModelPartMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
> [19:25:26] [main/WARN]: Force-disabling mixin 'features.render.entity.cull.EntityRendererMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
> [19:25:26] [main/WARN]: Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
> [19:25:26] [main/WARN]: Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [iris]) disables it and children
> [19:25:26] [main/WARN]: Force-disabling mixin 'features.render.world.sky.BackgroundRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
> [19:25:26] [main/WARN]: Force-disabling mixin 'features.render.world.sky.ClientWorldMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
> [19:25:26] [main/WARN]: Force-disabling mixin 'features.render.world.sky.WorldRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
> [19:25:26] [main/WARN]: Force-disabling mixin 'features.shader.uniform.ShaderProgramMixin' as rule 'mixin.features.shader.uniform' (added by mods [dashloader]) disables it and children
> [19:25:26] [main/INFO]: [SSPB] Indium detected. Option to toggle vanilla path block lighting will be enabled unless modded dirt path rendering is detected
> [19:25:26] [main/WARN]: Error loading class: net/mehvahdjukaar/betterlily/WaterloggedLilyBlock (java.lang.ClassNotFoundException: net/mehvahdjukaar/betterlily/WaterloggedLilyBlock)
> [19:25:26] [main/INFO]: [MemoryLeakFix] Will be applying 3 memory leak fixes!
> [19:25:26] [main/INFO]: [MemoryLeakFix] Currently enabled memory leak fixes: [targetEntityLeak, biomeTemperatureLeak, hugeScreenshotLeak]
> [19:25:26] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/occlusion/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/occlusion/BlockOcclusionCache)
> [19:25:26] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/occlusion/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/occlusion/BlockOcclusionCache)
> [19:25:26] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$Internal (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$Internal)
> [19:25:26] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$Internal (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$Internal)
> [19:25:27] [main/INFO]: Searching for graphics cards...
> [19:25:27] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.2.0).
> [19:25:28] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=AMD, name=Radeon RX 580 Series, version=DriverVersion=31.0.21902.5]
> [19:25:28] [main/WARN]: Invalid registry value type detected for PerfOS counters. Should be REG_DWORD. Ignoring: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfOS\Performance\Disable Performance Counters.
> [19:25:29] [main/WARN]: @Final field field_22786:Ljava/util/List; in mixins.ipnext.json:MixinScreen from mod inventoryprofilesnext should be final
> [19:25:29] [main/WARN]: @Final field field_33815:Ljava/util/List; in mixins.ipnext.json:MixinScreen from mod inventoryprofilesnext should be final
> [19:25:29] [main/INFO]: Mixing client.MixinMinecraft from mixins/common/nochatreports.mixins.json into net.minecraft.class_310
> [19:25:29] [main/INFO]: Mixing client.MixinMinecraft from mixins/fabric/nochatreports-fabric.mixins.json into net.minecraft.class_310
> [19:25:29] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on golemfirststonemod.mixins.json:MixinMinecraftClient from mod golemfirststonemod::handler$dpl000$golemfirststonemod$inject_doAttack_swingDandoriItem exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
> [19:25:29] [main/INFO]: Instancing error handler class dev.isxander.debugify.mixinplugin.DebugifyErrorHandler
> [19:25:29] [main/ERROR]: Mixin apply for mod noxesium failed noxesium.mixins.json:info.MinecraftMixin from mod noxesium -> net.minecraft.class_310: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on resizeDisplay could not find any targets matching 'resizeDisplay' in net.minecraft.class_310. Using refmap fabric-refmap.json [PREINJECT Applicator Phase -> noxesium.mixins.json:info.MinecraftMixin from mod noxesium -> Prepare Injections ->  -> handler$gfh000$noxesium$resizeDisplay(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
> org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on resizeDisplay could not find any targets matching 'resizeDisplay' in net.minecraft.class_310. Using refmap fabric-refmap.json [PREINJECT Applicator Phase -> noxesium.mixins.json:info.MinecraftMixin from mod noxesium -> Prepare Injections ->  -> handler$gfh000$noxesium$resizeDisplay(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at jdk.internal.reflect.GeneratedConstructorAccessor54.newInstance(Unknown Source) ~[?:?]
> 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
> 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.24.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.24.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
> 	at vazkii.patchouli.client.handler.BookCrashHandler.appendToCrashReport(BookCrashHandler.java:23) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
> 	at net.minecraft.class_6396.handler$gjd000$patchouli$addContext(class_6396.java:1516) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_6396.<init>(class_6396.java:58) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_128.<init>(class_128.java:34) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_128.method_24305(class_128.java:274) ~[client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:164) ~[Fabric%201.20.1.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.24.jar:?]
> [19:25:29] [main/ERROR]: Minecraft has crashed!
> net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_310 failed
> 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.24.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.14.24.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.24.jar:?]
> Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_310 failed
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.24.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.24.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
> 	at vazkii.patchouli.client.handler.BookCrashHandler.appendToCrashReport(BookCrashHandler.java:23) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
> 	at net.minecraft.class_6396.handler$gjd000$patchouli$addContext(class_6396.java:1516) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_6396.<init>(class_6396.java:58) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_128.<init>(class_128.java:34) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_128.method_24305(class_128.java:274) ~[client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:164) ~[Fabric%201.20.1.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
> 	... 2 more
> Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.24.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.24.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
> 	at vazkii.patchouli.client.handler.BookCrashHandler.appendToCrashReport(BookCrashHandler.java:23) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
> 	at net.minecraft.class_6396.handler$gjd000$patchouli$addContext(class_6396.java:1516) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_6396.<init>(class_6396.java:58) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_128.<init>(class_128.java:34) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_128.method_24305(class_128.java:274) ~[client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:164) ~[Fabric%201.20.1.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
> 	... 2 more
> Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [noxesium.mixins.json:info.MinecraftMixin from mod noxesium] from phase [DEFAULT] in config [noxesium.mixins.json] FAILED during APPLY
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.24.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.24.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
> 	at vazkii.patchouli.client.handler.BookCrashHandler.appendToCrashReport(BookCrashHandler.java:23) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
> 	at net.minecraft.class_6396.handler$gjd000$patchouli$addContext(class_6396.java:1516) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_6396.<init>(class_6396.java:58) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_128.<init>(class_128.java:34) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_128.method_24305(class_128.java:274) ~[client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:164) ~[Fabric%201.20.1.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
> 	... 2 more
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on resizeDisplay could not find any targets matching 'resizeDisplay' in net.minecraft.class_310. Using refmap fabric-refmap.json [PREINJECT Applicator Phase -> noxesium.mixins.json:info.MinecraftMixin from mod noxesium -> Prepare Injections ->  -> handler$gfh000$noxesium$resizeDisplay(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at jdk.internal.reflect.GeneratedConstructorAccessor54.newInstance(Unknown Source) ~[?:?]
> 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
> 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.24.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.24.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
> 	at vazkii.patchouli.client.handler.BookCrashHandler.appendToCrashReport(BookCrashHandler.java:23) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
> 	at net.minecraft.class_6396.handler$gjd000$patchouli$addContext(class_6396.java:1516) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_6396.<init>(class_6396.java:58) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_128.<init>(class_128.java:34) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_128.method_24305(class_128.java:274) ~[client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:164) ~[Fabric%201.20.1.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]

**Comment by InLieuOfLuna** [comment]
Sorry for not responding to this, this does not appear to be an issue with find, it seems like Noxesium was running into a critical failure
